# Must be installed
install.packages("devtools")
if(!require("roxygen2"))install.packages("roxygen2")
library(roxygen2) # Read in the roxygen2 R package
roxygenise()      # Builds the help files

# Generated by roxygen2: do not edit by hand


# FUNCTION NAMES TO EXPORT
#export(C_to_F)
#export(F_to_C)
# functions to .Rd

#library(devtools) # Make sure that the devtools library is loaded
#install_github("StirlingCodingClub/SCC_R_package")

#library(SCCTempConverter)
#F_to_C(30)
#----------------

#### TEST DATA

matrix1 <- read.csv("../stud/7sem/kursinis2/ewas/EWAS_Atlas_cohorts.tsv", sep = "\t",
                    header = TRUE)[1:1000,]
matrix2 <- read.csv("../stud/7sem/kursinis2/ewas/EWAS_Atlas_associations.tsv",sep = "\t",
                    header = TRUE)[1:1000,]
matrix3 <- read.csv("../stud/7sem/kursinis2/ewas/EWAS_Atlas_studies.tsv", sep = "\t",
                    header = TRUE)[1:1000,]
matrix4 <- read.csv("../stud/7sem/kursinis2/ewas/EWAS_Atlas_probe_annotations.tsv", sep = "\t",
                    header = TRUE)[1:1000,]

saveRDS(matrix1, "mockdata/matrix1.rds")
saveRDS(matrix2, "mockdata/matrix2.rds")
saveRDS(matrix3, "mockdata/matrix3.rds")
saveRDS(matrix4, "mockdata/matrix4.rds")

head(as.data.frame(matrix1))
