
#' Leave only one arrow between same nodes
#'
#' @param df A dataframe from makeConnections function
#' @return A modified dataframe
#' @example
#' df <- hideArrows(df)
#' @export
hideArrows <- function(df, minLength = 0){
  for(i in 1:nrow(df)){
    row <- df[i,]
    check <- which(((df$from == row$to) & (df$to == row$from)) |
                     ((df$count < minLength) & (df$from != 1)))
    if ((length(check) > 0 & df$arrows[i] != "")){
      df[check,"arrows"] <- ""
      df[check,"to"] <- 0
    }
  }
  return(df)
}

#hideNodes <- function(df){
  #for(i in 1:nrow(df)){
  #
  #  if(!((unique(df$to %in% df$id[i])) &
  #       (df$id != 1)))
  #  df$show[i] <- df$to %in% df$id[i]
  #    ifelse(!((unique(df$to %in% df$id[i])) &
  #                         (df$id != 1)), FALSE, TRUE)
  #}
#  return(df)
#}



#' Make nodes for visNetwork
#'
#' @param df A dataframe from function makeConnections
#' @return A new dataframe of nodes that will be used in visNetwork
#' @example
#' nodes <- makeNodes(df)
#' @export
makeNodes <- function(df){
  df <- df[union(df$from[df$to > 0],df$to),]
  nodes <- data.frame(id = df$id,
                      group = df$trait,
                      label = df$PMID,
                      value = df$count,
                      shape = df$shape,
                      title = apply(df, 1, function(x)
                        paste(x["Study.id"],"<br>",x["trait"], sep = "\n")),
                      color = df$color
                      #shadow = FALSE
                      )
  return(nodes)
}

#' Make edges for visNetwork
#'
#' @param df A dataframe from function makeConnections()
#' @return A new dataframe with edges for visNetwork
#' @example
#' edges <- makeEdges(df)
#' @export
makeEdges <- function(df, len){
  edges <- data.frame(from = df$from,
                      to = df$to,
                      value = df$coef,
                      color = df$edgeCol,
                      #length = 200,
                      #arrows = df$arrows,
                      #dashes = FALSE,
                      title = df$coef
                      #smooth = FALSE,
                      #shadow = FALSE
                      )
  if(len > 0){
    edges$length = len
  }
  return(edges)
}

#' Get visNetwork plot
#'
#' @param data A dataframe from function makeConnections()
#' @param save Set to FALSE by default, must be specified as YES
#' to save a graph as html
#' @param path A path to a folder where the graph should be saved.
#' Will not be used if save is set to FALSE
#' @param name A name for plot to be saved in file. Will bot be used
#' if save is set to FALSE
#' @return A plot visNetwork graph
#' @examples
#' network <- getVisNetwork(data)
#' network <- getVisNetwork(data, TRUE, "C:/../home/test.html", "save.html")
#' @export
getVisNetwork <- function(data, edgeLen = 100, len = 0, save = FALSE, path){
  if(nrow(data) == 0){
    print("There are no networks to show.")
  }
  library(visNetwork)
  data$arrows <- "to"
  data <- hideArrows(data, len)
  nodes <- makeNodes(data)
  edges <- makeEdges(data, edgeLen)



  v <-visNetwork(nodes, edges, width = "100%" , height = 700) %>%
    visNodes(scaling = list(label = list(enabled = T))) %>%
    visClusteringOutliers(1)
  if(save){
    visSave(v, path,
            selfcontained = TRUE, background = "white")
  }
  return(v)
}

#' Generate infromation from connection data
#'
#' @param data A dataframe that was generated by makeConnections
#' @param id A single number or an array of numbers used in data made
#' for connections - id. Either id or study should be provided
#' @param study A single name or an array of study names that will be included
#' @return Returns a dataframe with id, connecting from id, id's study name,
#' id's trait, connecting to id, id's study name, trait and overlap count
#' between them - matching cg positions count
#' @examples
#' df <- getSimilarTraits(data2, study = c("ES00034, "ES00035))
#' df <- getSimilarTraits(data2, c(1,2,3,42))
#' @export
getSimilarTraits <- function(data,study = 0){
  tdata <- data
  if (typeof(study) == "character"){
    id <- data$id[data$Study.id %in% study][1]
    tdata <- data[(data$from %in% id) |
                ((data$from == 1) & (data$to %in% id)),]
  }
  dat <- data.frame("id" = numeric(), "f.id" = numeric(),
                   "fStudy.id" = character(), "f.trait" = character(),
                   "t.id" = numeric(), "tStudy.id" = character(),
                   "t.trait" = character(), "coef" = numeric(),
                   "count" = numeric(), "PMID" = character(),
                   "Ancestry" = character(),
                   stringsAsFactors = FALSE)
  for(i in 1:nrow(tdata)){
    tid <- tdata$to[i]
    dat[i,] <- c(tdata$id[i], tdata$from[i], tdata$Study.id[i],
                 tdata$trait[i], tdata$to[i], data$Study.id[tid],
                 data$trait[tid], tdata$coef[i], tdata$count[i],
                 tdata$PMID[i], tdata$Ancestry[i])
  }
  return(dat)
}

#######################
########################
#########################

#' A dataframe for stacked histogram
#'
#' @param data A data matrix with no modifications
#' @param positions An array of cg positions in new study
#' @param traits An array of trait names that was to be compared to.
#' By default set to 0 - compare to all
#' @return A dataframe for visNetwork graph
#' @example
#' df <- dfForHistogram(data, positions)
#' @export
dfForHistogram <- function(data, positions = 0, traits = 0){
  library(dplyr)
  library(tidyverse)
  library(ggplot2)

  traitst <- traits
  traits <- unique(data$Trait)
  if (typeof(traitst) == "character"){
    traits <- unique(traitst)
    data <- data[data$Trait %in% traits,]
  }
  posd <- unique(positions)
  pos <- unique(data$Probe.id)
  if (typeof(posd) == "character"){
    data <- data[data$Probe.id %in% posd,]
    pos <- unique(positions)
  }

  df <- data.frame("Probe.id" = character(), "Trait" = character(),
             "count" = numeric(), stringsAsFactors = FALSE)
  id <- 1
  for(i in 1:length(pos)){
    for(j in 1:length(traits)){
      count <- length(data$Probe.id[data$Probe.id == pos[i] &
                                    data$Trait == traits[j]])
      if(count > 0){
        df[id,1] <- pos[i]
        df[id,2] <- traits[j]
        df[id,3] <- count
        id <- id +1
      }
    }
  }
  return(df)
}

#' A stacked histogram
#'
#' @param df A dataframe from function dfForHistrogram
#' @param minCount A number that will limit position count in traits for show
#' @return A ggplot plot
#' @example
#' hist <- stackedHistogram(df, 150)
#' @export
stackedHistogram <- function(df, minCount = 1, save = FALSE, path){
  library(highcharter)
  hc <- df[df$count > minCount,] %>%
    hchart(
      'column', hcaes(x = 'Probe.id', y = 'count', group = 'Trait'),
      stacking = "normal",
    ) %>%
    hc_xAxis(title = list(text = 'CG positions'))

  if(save){
    saveWidget(hc, path)
  }
  return(hc)
}


#' Print basic instructions how to
#'
#' @example
#' instruction()
#' @export
instructions <- function(){
  print('HOW TO USE')
  print('---------------')
  print('data <- readRDS("mockdata/wholeMatrix.rds")')
  print('Preferably save cg positions in an array')
  print('Specific studies can be chosen too')
  print('data1 <- processData(data, positions, studies)')
  print('traits <- traitTable(data)')
  print('data2 <- makeConnections(data1, positions, studyName, traits)')
  print('similar <- getSimilarTraits(data2, id = 1)')
  print('network <- getVisNetwork(data2)')
  print('df <- dfForHistogram(data, positions)')
  print('hist <- stackedHistogram(df)')
}

#library(networkD3)
#library(dplyr)


# A connection data frame is a list of flows with intensity for each flow
#links <- data.frame(
#  source=data$Trait[c(1,100:110, 200:250)],
#  target=data$Probe.id[c(1,100:110, 200:250)],
#  value=1
#)

#nodes <- data.frame(
#  name=c(as.character(links$source),
#         as.character(links$target)) %>% unique()
#)
# With networkD3, connection must be provided using id,
#not using real name like in the links dataframe.. So we need to reformat it.
#links$IDsource <- match(links$source, nodes$name)-1
#links$IDtarget <- match(links$target, nodes$name)-1

#p <- sankeyNetwork(Links = links, Nodes = nodes,
#                   Source = "IDsource", Target = "IDtarget",
#                   Value = "value", NodeID = "name",
#                   sinksRight=FALSE)
#p
##library(htmlwidgets)
##library("savePlotAsPng")
##install.packages("savePlotAsPng")
##savePlotAsPng(v, file = "mockdata/v.png", width = 600, height = 480)

#saveWidget(v, file = "mockdata/v.html")

#install.packages("highcharter")
#%>%
 # hc_colors(c("#0073C2FF", "#EFC000FF"))
